unb = University.create(name: 'UnB')
gama = Campus.create(name: 'Gama', university: unb)
fga = Department.create(name: 'FGA', campus: gama)
swe = Course.create(name: 'Engenharia de Software', campus: gama)
ije = Subject.create(name: 'Introdução a Jogos Eletrônicos', department: fga)
a_class = SubjectClass.create(name: 'A', subject: ije)
tuesday_14_to_16 = Schedule.create(start_time: '', end_time: '')
thursday_14_to_16 = Schedule.create(start_time: '', end_time: '')